Barricades Rework [SEMI-MODULAR]
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #119
Opened 2023-11-12 13:44 UTC by fe-ed

## Добавляет железную дверцу

![Снимок экрана 2023-11-11 184907](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/125674585/39fcd8f0-4605-4342-845f-d14daa93233c)

2023-11-13 13:44 UTC, Dgeen requested changes
Модульность было бы неплохо подправить

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("metal folding barricade", /obj/structure/barricade/plasteel/metal, 6, time = 10 SECONDS, max_per_turf = STACK_RECIPE_ONE_DIRECTIONAL_PER_TILE, on_floor = TRUE, skill_req = SK
Закоментить оригинал через /**/, выделить изменения через //RUTGMC EDIT CHANGE BEGIN/END (альтернативно закоментить весь глобал лист и перенести его в модульную папку)

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	"folding metal barricade" = image('icons/Marine/barricades.dmi', icon_state = "folding_metal_0"), //RUTGMC ADDON
Смотри комментарий 1

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +
Это в модульную папку

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +
Это в модульную папку

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +*/
Здесь убрать изменения оригинального кода

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +
Это в модульную папку

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/items/stacks/stack.dm
> +		building_time -= clamp(R.time * ( user.skills.getRating(SKILL_CONSTRUCTION) - R.skill_req ) * 0.20, 0 , 0.85 * building_time) // -20% time each extra skill point //RUTGMC EDIT 40% > 20%
Закоментить оригинал, выделить изменения через //RUTGMC EDIT CHANGE

2023-11-13 13:44 UTC, Dgeen commented on code/game/objects/structures/barricade.dm
> +	//RUTGMC EDIT END
Смотри комментарий выше

2023-11-13 13:44 UTC, Dgeen commented on code/modules/mining/remote_fob/remote_fob_actions_misc.dm
> +	if(console.plasteel_remaining < 6) //RUTGMC EDIT
Аналогично

2023-11-13 13:44 UTC, Dgeen commented on code/modules/mining/remote_fob/remote_fob_actions_misc.dm
> +	console.plasteel_remaining -= 6 //RUTGMC EDIT
Аналогично

2023-11-13 13:44 UTC, Dgeen commented on code/modules/mining/remote_fob/remote_fob_computer.dm
> +	var/plasteel_remaining = 120 //RUTGMC EDIT
И здесь тоже

2023-11-13 13:44 UTC, Dgeen commented on code/modules/mining/remote_fob/remote_fob_computer.dm
> +	plast_folding_cade = new()
Ну ты понял

2023-11-13 13:44 UTC, Dgeen commented on code/modules/mining/remote_fob/remote_fob_computer.dm
> +	QDEL_NULL(plast_folding_cade)
И здесь также

2023-11-13 13:44 UTC, Dgeen commented on code/modules/mining/remote_fob/remote_fob_computer.dm
> +		actions += plast_folding_cade
Закоментить оригинал, добавления отдельной строчкой

2023-11-13 13:46 UTC, fe-ed commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("metal folding barricade", /obj/structure/barricade/plasteel/metal, 6, time = 10 SECONDS, max_per_turf = STACK_RECIPE_ONE_DIRECTIONAL_PER_TILE, on_floor = TRUE, skill_req = SK
Комменты в листе не работают, ломает код почему-то

2023-11-13 13:55 UTC, Dgeen commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe("metal folding barricade", /obj/structure/barricade/plasteel/metal, 6, time = 10 SECONDS, max_per_turf = STACK_RECIPE_ONE_DIRECTIONAL_PER_TILE, on_floor = TRUE, skill_req = SK
В таком случае комменть весь лист делай сноску о переносе в другую папку и переноси в модуль

2023-11-16 06:30 UTC, Blundir requested changes
Комменты валидны

2023-11-20 12:56 UTC, Dgeen approved these changes
В принципе пойдет думаю

2023-11-20 13:03 UTC, merged