Buff scout cloak [NON-MODULAR]
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #124
Opened 2023-11-13 10:32 UTC by Ghostkokos

## About The Pull Request

Перебалансировка всеми забытого плаща скаута
Теперь при хоть бе заместо траты энергии вы будете получать её 1 в секунду
Повышенна незаметность во всех трёх режимах, хоть ба, бег, стояние.
(так же планировалось добавить трейт на тихую хоть бу но это может быть добавлено в будущем)

## Why It's Good For The Game

Делает скаутку чуть более играбельнее, в основном проблема скаутки была в том что ты при любом движении тратил дохуя энергии получая буквально 20% незаметности, это слегка поправили оффы на ребейзе дав ей 3 секундный практический фулл инвиз при активации но тем неменее не зыскалла особой популярности, это изменение даст плащу вторую жизнь.

:cl:
add: Added new mechanics or gameplay changes
balance: rebalanced something
code: changed some code
/:cl:

2023-11-17 11:52 UTC, fe-ed requested changes

2023-11-17 11:52 UTC, fe-ed commented on code/__DEFINES/objects.dm
> +#define SCOUT_CLOAK_STILL_ALPHA 10 //RUTGMС EDIT
В принципе одобряю, но альфу невидимости не стоит менять

2023-11-17 11:56 UTC, Dgeen requested changes
Оригинальные дэфайны не изменяем, а закомменчиваем используя /**/, свой вариант прописываем либо ниже оригинала, либо в модульной папке

2023-11-17 12:36 UTC, fe-ed approved these changes

2023-11-20 16:46 UTC, Dgeen approved these changes

2023-11-22 17:31 UTC, merged