Убирает общий КД у флинга и граба Шрайка
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #142
Opened 2023-11-18 18:30 UTC by Waselon

Убирает общий КД у флинга и граба Шрайка

2023-11-18 20:38 UTC, Dgeen commented
И мы снова придем к не понерфенной шрике с тремя станами на которую уже жаловались до ребейза, гениально

2023-11-19 05:26 UTC, Waselon commented
> И мы снова придем к не понерфенной шрике с тремя станами на которую уже жаловались до ребейза, гениально

могу сделать общий КД поменьше, секунд 5. Потому что полное КД в 45 секунд убивает всю суть примо

2023-11-19 10:43 UTC, fe-ed requested changes
Оставь хотя бы 3 секунды

2023-11-19 10:56 UTC, fe-ed approved these changes

2023-11-20 05:30 UTC, Blundir approved these changes

2023-11-20 05:30 UTC, merged