[MODULAR] Returns t500 to vendor with weapons
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #146
Opened 2023-11-19 10:09 UTC by Ghostkokos

## About The Pull Request
Возвращает кейс с т500 и уникальными патронами "queen killer"
Частично исправляет спрайт пулек т500
Вместе с кейсом в вендоре с одеждой в разделе пояса появился и пояс для т500.
Слегка улучшает патроны queen killer  с нынешними изменениями квины.
Увеличен дамаг по квине. 30>40
Теперь накладывает стагер на одну секунду при попадании по квине.
## Why It's Good For The Game
Закрывать т500 за карго так тем более  не давая патронов не обычных не  queen killer звучит глупо, сейчас в нынешнем в виде она не играбельна по причине отсутствия боеприпасов, люди попросту забыли про неё и это не весело :(.

## Changelog
Делает т500 более играбельным
Возвращает уникальные патроны "queen killer"

:cl:
add: Added new mechanics or gameplay changes
balance: rebalanced something
fix: fixed a few things
code: changed some code
/:cl:

2023-11-19 10:40 UTC, fe-ed requested changes

2023-11-19 10:40 UTC, fe-ed commented on modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
> +		staggerstun(M, P, stagger = 1, slowdown = 0, knockback = 0)
Ну, стаггер по т4 касте из револьвера с уроном 140 и пенетрой 40 это.. Слишком

2023-11-19 10:40 UTC, fe-ed commented on modular_RUtgmc/code/game/objects/machinery/vending/marine_vending.dm
> +/obj/machinery/vending/weapon
Зря ты наверное все вендоры переопределил, спроси у Блундира на это счет.

2023-11-19 10:59 UTC, fe-ed commented on modular_RUtgmc/code/modules/projectiles/ammo_datums.dm
> +		staggerstun(M, P, stagger = 0, slowdown = 0, knockback = 0)
Ты мог просто убрать прок стаггера....

2023-11-19 11:04 UTC, fe-ed approved these changes

2023-11-20 14:45 UTC, Dgeen approved these changes

2023-11-20 14:45 UTC, merged