Added new sound emotions
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #154
Opened 2023-11-20 20:46 UTC by RagaDama

## About The Pull Request

Добавлены новые звуковые эмоции для людей: плач, вздох, стон, зевок.

## Why It's Good For The Game

Повышаем погружение в атмосферу игры. Теперь потеря ФОБа будет под вздохи и рыданья ФК.

## Changelog

:cl:
soundadd
/:cl:

2023-11-23 13:20 UTC, Blundir commented on code/modules/mob/living/carbon/human/emote.dm
> -/datum/emote/living/carbon/human/giggle
А зачем ты их все удалил?

2023-11-23 13:20 UTC, Blundir commented on .vscode/settings.json
> +	"dotnet.preferCSharpExtension": true
Зачем?

2023-11-25 13:14 UTC, LoneAsket requested changes
Исправляй.

2023-11-25 13:14 UTC, LoneAsket commented on code/modules/mob/living/carbon/human/emote.dm
>  /datum/emote/living/carbon/human/laugh
Всё что ты выше удалил нельзя удалять. Это оригинал. Его нужно оставлять нетронутым. Вся перезапись идет в модульном файле.

2023-11-25 13:14 UTC, LoneAsket commented on .vscode/settings.json
> +	"dotnet.preferCSharpExtension": true
"tgstationTestExplorer.project.DMEName": "tgmc.dme" (без запятой)
оставить.
Остальное снести.
Ты вообще не должен был трогать этот файл.

2023-11-26 11:18 UTC, Dgeen commented on code/modules/mob/living/carbon/human/emote.dm
> +
Как уже сказали оригинальный код должен быть не тронутым, а ты зачем-то перемешал все эмоуты

2023-12-01 16:07 UTC, Dgeen approved these changes

2023-12-01 17:03 UTC, Blundir approved these changes

2023-12-01 17:09 UTC, merged