[FIX][MODULAR] Allow beret's and helmet for robot
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #160
Opened 2023-11-23 01:09 UTC by LoneAsket

## About The Pull Request

## Why It's Good For The Game

## Changelog

:cl:
add: Added new mechanics or gameplay changes
add: Added more things
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-11-23 09:22 UTC, fe-ed reviewed
Не думаю что новые флаги это хорошая идея в реалиях ребейза, но чтобы наверняка спроси еще у DB на этот счет

2023-11-23 17:24 UTC, LoneAsket commented
> Шлема не разрешаются

Всё исправлено, одобряй, начальник.

2023-11-23 18:03 UTC, Dgeen requested changes

2023-11-23 18:03 UTC, Dgeen commented on modular_RUtgmc/code/modules/clothing/head/head.dm
> +	species_exception = list(/datum/species/robot)
Есть причина, по которой ты отдельно прописываешь исключение для каждого тгмс берета, вместо прописывания его для одного родительского тгмс берета? Аналогичный вопрос для беретов, офицерских шапок и бандан

2023-11-23 18:29 UTC, Helg2 commented
https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/issues/162

2023-11-23 18:51 UTC, LoneAsket commented
> #162
Это уже решено в этом ПРе. Не стоит беспокоиться.

2023-11-23 19:08 UTC, LoneAsket commented on modular_RUtgmc/code/modules/clothing/head/head.dm
> +	species_exception = list(/datum/species/robot)
Переделал

2023-11-23 19:08 UTC, LoneAsket commented on modular_RUtgmc/code/modules/clothing/head/head.dm
> +	species_exception = list(/datum/species/robot)
Переделал

2023-11-23 19:09 UTC, Dgeen approved these changes

2023-11-24 23:38 UTC, LegateBebranius commented
Что насчёт Warning Cone? Оно тоже щитается шляпой, а роботы носить не могут. НЕПОРЯДОК.
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/22df2c7e-be6e-4dfb-964f-ac59d9985a5a)
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/1e484480-d2da-4fb6-a249-c9509661c663)
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/143013516/616bfa23-d170-420c-a43a-535c95b7ca8f)

2023-11-25 01:35 UTC, LoneAsket commented
> Что насчёт Warning Cone? Оно тоже щитается шляпой, а роботы носить не могут. НЕПОРЯДОК. ![image](https://private-user-images.githubusercontent.com/143013516/285554406-22df2c7e-be6e-4dfb-964f-ac59d9985a5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NzYzNDUsIm5iZiI6MTcwMDg3NjA0NSwicGF0aCI6Ii8xNDMwMTM1MTYvMjg1NTU0NDA2LTIyZGYyYzdlLWJlNmUtNGRmYi05NjRmLWFjNTlkOTk4NWE1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwMTM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODkzYzU1ZGI4ODFlMGM2MDQ5YTRlOTYwNjhiZGQxMWMzZjc5ZTFmYjNmNTQ5NjYwYjdmNTlmYmZjNDg4NDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PT4NbSCd4kkAh6Io_UVY5TV1e6POf6NCFH4RNXgHxm0) ![image](https://private-user-images.githubusercontent.com/143013516/285554415-1e484480-d2da-4fb6-a249-c9509661c663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NzYzNDUsIm5iZiI6MTcwMDg3NjA0NSwicGF0aCI6Ii8xNDMwMTM1MTYvMjg1NTU0NDE1LTFlNDg0NDgwLWQyZGEtNGZiNi1hMjQ5LWM5NTA5NjYxYzY2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwMTM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjJlNjEwN2M1ODgzZmMzMjZkMTk4NmM5N2FhZDcxZjFjOTRhNmFlMDk3ZjU2NDhhMTYxYzhiODk3OWQzZTY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._8jirxp6tQVL-iA4n4VjukO3JyMdqNx1B9TK7FPlEqU) ![image](https://private-user-images.githubusercontent.com/143013516/285554430-616bfa23-d170-420c-a43a-535c95b7ca8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NzYzNDUsIm5iZiI6MTcwMDg3NjA0NSwicGF0aCI6Ii8xNDMwMTM1MTYvMjg1NTU0NDMwLTYxNmJmYTIzLWQxNzAtNDIwYy1hNDNhLTUzNWM5NWI3Y2E4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQwMTM0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmQ1NWZjN2JjMjZkZjgyODVmN2EzZTE5MzJlZjZmZDFkYTQzYjY5OTg3NzZhODQwZmQ5ZWRmNDMwZDE3NjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qLlfye6nGdvFLCWIH5UiZ6NETTq4KK5OnKNw2iOQ_J0)

Список огласи сразу уж, всех айтемов, которые хотели бы чтобы я проверил на носимость на голове. А то по коду это раскидано довольно сильно.

2023-11-25 06:23 UTC, LoneAsket reviewed
изменил

2023-11-25 06:23 UTC, LoneAsket commented on modular_RUtgmc/code/modules/mob/living/carbon/human/species.dm
Переделал. Почему-то не убирается ебучий реквест чейндж. ХОТЯ ЭТО УЖЕ УБРАНО, БЛЯДЬ.

2023-11-28 05:48 UTC, merged