[FIX][MODULAR] Fix icon's for belts
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #166
Opened 2023-11-24 09:29 UTC by LoneAsket

## About The Pull Request
Фикс https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/issues/155
Спрайта пояса(+двушка) в слоте нагрудника нет в спрайтах, поэтому там он так и останется без отображения.

Вальгалле тестил стандартные пояса + некоторые нестандартные. Всё работало хорошо.
Пришлось вставлять спрайты с оффов в модульную папку. Какой-то гений с оффов догадался в функции сделать добавление всем спрайтам _full вместо _g , а поправить спрайтам названия не догадался. Так еще потом и наши изменения сверху, так что сейчас всё +- приведено к единому виду.

## Тестирование
В Вальгалле тестил стандартные пояса + некоторые нестандартные. Всё работало хорошо.

2023-11-24 10:02 UTC, Helg2 commented on modular_RUtgmc/code/game/objects/items/storage/holsters.dm
> +	item_icons = list(
Можно же по-идее и без этого, оно вроде само выставляется

2023-11-24 10:38 UTC, LoneAsket commented on modular_RUtgmc/code/game/objects/items/storage/holsters.dm
> +	item_icons = list(
Для белтов уж лучше явно переопределить, ибо учитывая, что там в функции идет при апдейт иконе переприсваивание самому себе с тегом _full, я хуй его знает откуда оно резко подцепит, учитывая что в оригинале будет ссылка на ориг с доп тегом, а итем айкон будет ссылаться на модулярку. Уж проще всё подвести к одному.
По идее это может сработать, но я решил сделать это более явно.

2023-11-25 10:26 UTC, Blundir approved these changes

2023-11-25 10:28 UTC, Blundir requested changes
А хотя стоп.
Во-первых ты удалил то что было в файле до этого
Во-вторых, почему только на конкретные проблемные пояса не сделать это?
Да и вроде оффы это пофиксили уже

2023-11-25 12:51 UTC, LoneAsket commented
Пофиксил.

2023-11-28 05:48 UTC, merged