Quickbuilds are now personal on distress.
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #190
Opened 2023-11-29 09:14 UTC by Helg2

На дистресс квикбилды персональные, на краше их нету, как и должно, на нюке они общие.

2023-11-30 12:53 UTC, Dgeen requested changes

2023-11-30 12:53 UTC, Dgeen commented on modular_RUtgmc/code/controllers/subsystem/processing/resinshaping.dm
> +		return FALSE
В общем режиме возможно перерабатывать плевки хла в общие очки, добавь фикс из этого пра https://github.com/tgstation/TerraGov-Marine-Corps/pull/13332

2023-11-30 12:53 UTC, Dgeen commented on modular_RUtgmc/code/game/turfs/walls/resin.dm
> +	if(CHECK_BITFIELD(SSticker.mode.flags_round_type, MODE_ALLOW_XENO_QUICKBUILD) && SSresinshaping.should_refund(src, X))
```suggestion
	if(CHECK_BITFIELD(SSticker.mode?.flags_round_type, MODE_ALLOW_XENO_QUICKBUILD) && SSresinshaping.should_refund(src, X))
```

2023-11-30 13:38 UTC, Dgeen commented on code/__DEFINES/~RUtgmc_defines/mode.dm
> +
В /datum/game_mode/ сделай отдельный var/flags_quickbuild_type (или var/flags_round_type_ru не важно), в котором будут содержаться наши флаги (в данном случае тип квикбилда), соответственно нюка и дистресс будут переопределять эту переменную, и проверки на флаги типов постройки тоже будут по новой переменной

2023-12-01 10:56 UTC, Dgeen approved these changes

2023-12-01 19:54 UTC, fe-ed approved these changes

2023-12-03 14:27 UTC, merged