Ghostattack() for clone vat.
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #196
Opened 2023-11-30 13:02 UTC by Helg2

Теперь если пропустил алёрт по поводу нового клона, можно будет из гостов нажать на колбу и стать клоном.

2023-11-30 15:27 UTC, Blundir approved these changes

2023-12-02 10:36 UTC, Dgeen requested changes

2023-12-02 10:36 UTC, Dgeen commented on modular_RUtgmc/code/game/objects/machinery/cloning/cloning.dm
> +	return TRUE
Вместо transfer_mob используй take_over

2023-12-02 13:46 UTC, Dgeen approved these changes

2023-12-02 13:47 UTC, merged