Cuts primo time in half.
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #214
Opened 2023-12-07 08:50 UTC by Helg2

т1: 210 (7 минут) <-- 420 тиков (14 минут)
т2: 420 (14 минут) <-- 840 ( 28 минут)
т3: 840 (28 минут) <--  1750 (58 минут)
Считал по формуле `Тики * 2 / 60`
За время ожидания примо, ты сможешь сходить в магазин туда и обратно, и примо всё равно не будет.
Зачастую раунды не длятся столько чтобы т3 и получили примо апгрейд, и дожили до него.
Можно увеличить числа до 300, 450 и 900 для кратности.

2023-12-08 14:42 UTC, fe-ed approved these changes
Ну не знаю, слишком неоправданное повышение в 2 раза с каждым тиром, я бы сделал что-то менее значительное, 5 - 10 - 15 минут. 30 минут на Т3 это вообще смех.

2023-12-08 14:43 UTC, fe-ed requested changes
UPD

2023-12-11 09:23 UTC, Helg2 commented
@fe-ed @Dgeen

2023-12-11 09:37 UTC, fe-ed commented
Будет круто если сделаешь цены чуть более актуальными: т1: 600 т2: 700 т3: 800 т4: 700

2023-12-11 09:40 UTC, Helg2 commented
Ладно

2023-12-11 10:32 UTC, Blundir approved these changes

2023-12-11 10:32 UTC, merged