Puppteer sprite update
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #257
Opened 2023-12-17 13:02 UTC by Ghostkokos

По приказу свыше от Блун*ира портирование нового спрайта для puppteer завершено

2023-12-18 06:24 UTC, fe-ed approved these changes
Ничего про него не скажу, тестим

2023-12-19 11:46 UTC, fe-ed requested changes
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/125674585/8d58dfd4-622e-4efc-a6d6-627594dbf0b4)

2023-12-21 14:54 UTC, Blundir requested changes

2023-12-21 14:54 UTC, Blundir commented on code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
> +		adjustBruteLoss(-15) //adjustBruteLoss(-5) //RUTGMC EDIT
Модульно делай

2023-12-29 08:17 UTC, Ghostkokos commented
> ![image](https://private-user-images.githubusercontent.com/125674585/291576355-8d58dfd4-622e-4efc-a6d6-627594dbf0b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzgwNzYsIm5iZiI6MTcwMzgzNzc3NiwicGF0aCI6Ii8xMjU2NzQ1ODUvMjkxNTc2MzU1LThkNThkZmQ0LTYyMmUtNGVmYy1hNmQ2LTYyNzU5NGRiZjBiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwODE2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmY0Y2VlMGM0YTYwMzM4MTM5YTUxY2IyM2JiZjI1MDk3ZDdmYmJkNDAyYjJkMTQ0NTc5ZWE0NmJkNmQxOWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5TYCs-T9iFUZ70xXy9W8ehkeAigAXFY3Yf1qI4ma-cw)

![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/141329730/168b0455-3fe7-4729-996c-cb968fc356e8)

2023-12-29 14:51 UTC, fe-ed approved these changes

2023-12-29 14:54 UTC, Dgeen requested changes
Баффаем и так сильную касту, вот бы вы так над вдовой работали. Может сразу его в т3 перенесете с таким балансом

2023-12-29 15:50 UTC, Dgeen requested changes

2023-12-29 15:50 UTC, Dgeen commented on code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
> +//		adjustBruteLoss(-5)
Используй /**/, а также укажи что прок был перенесен в модуль

2023-12-29 15:50 UTC, Dgeen commented on modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
> +		adjustBruteLoss(-15)
Ты забыл удалить это когда переносил файл

2023-12-29 15:50 UTC, Dgeen commented on modular_RUtgmc/includes.dm
> +#include "code\modules\mob\living\carbon\xenomorph\castes\puppet\castedatum_puppet.dm"
Ещё раз. Не пихаем в конец файла, найди где оно должно быть в алфавитном порядке и вставь его туда

2023-12-30 10:12 UTC, Dgeen approved these changes

2023-12-30 12:59 UTC, Blundir approved these changes

2023-12-30 13:00 UTC, merged