Xenomorph Timelocks Lowered
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #269
Opened 2023-12-22 18:13 UTC by fe-ed

До: 
## 0 - 10 - 25 - 70 - 175

После:
## 0 - 5 - 15 - 30 - 50

2023-12-22 18:41 UTC, Dgeen requested changes
Мы не используем оффовские проки, все изменения вносить в модуль

2023-12-22 20:53 UTC, Dgeen approved these changes

2023-12-22 22:24 UTC, Blundir commented
Зачем?

2023-12-22 22:30 UTC, fe-ed commented
> Зачем?

Чтобы убрать заоблачные числа конечно же

2023-12-22 22:32 UTC, Blundir commented
> > Зачем?
> 
> Чтобы убрать заоблачные числа конечно же

Young - 10 hours (the same)
Mature - 25 hours (instead of 50)
Elder - 70 hours (instead of 100)
Ancient - 175+ (instead of 300)

Это из пра где их и так понижали, такие цифры вполне адекватны как по мне

2023-12-22 22:34 UTC, Blundir commented
А, я увидел кое-что, цифры из [этого пра](https://github.com/tgstation/TerraGov-Marine-Corps/pull/14481/files) выстави просто.

2023-12-23 07:03 UTC, fe-ed commented
Компромисс достигнут, можно мержить

2023-12-23 14:26 UTC, Blundir approved these changes

2023-12-23 14:26 UTC, merged