[MODULAR] sg-62 changes
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #300
Opened 2023-12-29 16:17 UTC by definitelynotspaghetti

## About The Pull Request
Сандеринг снижен с 5 до 1.
highimpact стаггер снижен 3 до 1 секунды.
tungsten стаггер снижен до 0.5.
Добавил коробку в лодаут вендор.

## Why It's Good For The Game
У пушки 40 дамага и 30 АП, такой высокий сандеринг ей ни к чему. Время стаггера тоже чересчур высоким получилось.

2023-12-30 08:37 UTC, fe-ed requested changes
Ты ей сделал сандеринг меньше чем у автомат смартганов, оставляй 3

2023-12-30 09:56 UTC, definitelynotspaghetti commented
> Ты ей сделал сандеринг меньше чем у автомат смартганов, оставляй 3

У неё урона и ап больше, чем у остальных. Если кому-то будет нужен сандеринг, то есть патроны на подствол с 5 сандера

2023-12-30 14:11 UTC, fe-ed commented
> > Ты ей сделал сандеринг меньше чем у автомат смартганов, оставляй 3
> 
> У неё урона и ап больше, чем у остальных. Если кому-то будет нужен сандеринг, то есть патроны на подствол с 5 сандера

Ты хочешь чтобы без подстволов она была неэффективна? АП не слишком помогает этим 40 урона, и она всё еще проигрывает все остальным смартган пушкам.

2023-12-30 16:32 UTC, fe-ed approved these changes

2023-12-31 00:26 UTC, Blundir approved these changes

2023-12-31 00:26 UTC, merged