M-sensor module for C-robot
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #340
Opened 2024-01-11 20:12 UTC by Ro2tCrab

По какой-то причине бобота обделили сенсором.
Исправляем.

2024-01-11 20:23 UTC, Helg2 commented
Ты смотрел как это выглядит на роботах? Решение придумал?

2024-01-11 20:34 UTC, Ro2tCrab commented
Хотя не, если там всего пару пикселей подправить - отредактируем.

2024-01-12 07:58 UTC, Blundir requested changes
Претензия валидна, пока спрайта не будет адекватного на это, мёрджа не будет

2024-01-12 11:50 UTC, fe-ed commented
Могу помочь со спрайтом

2024-01-16 09:37 UTC, Ro2tCrab commented
> Ты смотрел как это выглядит на роботах? Решение придумал?

Посмотрел.
Проблем вообще не вижу.
### Это на Комбат-ботах
![Screenshot_1](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/68421546/a4a884f0-5ee0-4243-b41a-cee5c9980236)
### Люди, для сравнения
![Screenshot_2](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/68421546/5080f64e-1959-44fc-9b0e-c2cc068e8da3)

2024-01-16 09:41 UTC, Ro2tCrab commented
Я бы понял если бы спрайт улетал значительно от спрайта шлема - это фикс.
У нас же тут сенсор выглядит как и на хуманах. Менять спрайт тут - за пределами самого фикса.

2024-01-16 10:22 UTC, Helg2 commented
Ну хуй знает.

2024-02-06 20:52 UTC, Ro2tCrab commented
> Проблем вообще не вижу.
> ### Это на Комбат-ботах
> ![Screenshot_1](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/68421546/a4a884f0-5ee0-4243-b41a-cee5c9980236)
> ### Люди для сравнения
> ![Screenshot_2](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/68421546/5080f64e-1959-44fc-9b0e-c2cc068e8da3)
> 

@Blundir , так что с этим ПРом?

2024-02-07 21:50 UTC, fe-ed commented
> @Blundir , так что с этим ПРом?
> Небольшой фикс стоит целый месяц.

Почему Блундира спрашиваешь, а не автора пра?

2024-02-07 22:09 UTC, Ro2tCrab commented
> > @Blundir , так что с этим ПРом?
> > Небольшой фикс стоит целый месяц.
> 
> Почему Блундира спрашиваешь, а не автора пра?
> 

А зачем мне спрашивать самого себя?
Спрайты, как видно на скрине, выглядят в идентичности как у маринов.
Ревью делал Блундир, следовательно - вопрос.

2024-02-07 23:14 UTC, fe-ed commented
> > Почему Блундира спрашиваешь, а не автора пра?
> > 
> 
> А зачем мне спрашивать самого себя?
> Спрайты, как видно на скрине, выглядят в идентичности как у маринов.
> Ревью делал Блундир, следовательно - вопрос.
Я с мобилки не увидел чей это ПР, думал он от Аскета

2024-02-27 13:57 UTC, Blundir approved these changes

2024-02-27 13:57 UTC, merged