[MODULAR] Weather buff
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #363
Opened 2024-01-18 17:44 UTC by definitelynotspaghetti

## About The Pull Request
Буря на Биг Реде теперь наносит ксеносам 20 урона(было 6), марам 8
Кислотный дождь на ЛВ наносит ксенам 20 урона(было 7)

## Why It's Good For The Game
Будет лучше, если погодные условия на этих карта будут влиять на обе стороны, а не только на маров. Сейчас же ксеносы легко перебивают урон регеном.

2024-01-18 18:53 UTC, fe-ed requested changes
Много, не делай больше х2

2024-01-18 19:21 UTC, definitelynotspaghetti commented
> Много, не делай больше х2

Тогда им всё так же будет похуй на урон

2024-01-18 19:27 UTC, fe-ed commented
> > Много, не делай больше х2
> 
> Тогда им всё так же будет похуй на урон

Можешь тогда сразу учитывать маров под фулл химией

2024-01-19 08:40 UTC, lorianss commented
Что насчёт того, что бы увеличить урон от бури, но не увеличивать урон он дождя?
Лв это анти ксено карта, возможно даже худшая в билде, пусть дождь будет плюсом для них на этой карте.
К тому же достаточно логично, что ксеносы которые буквально тушатся в кислотных колодцах
Мало получают урон от кислоты.

2024-01-19 10:57 UTC, nikotin34 commented
Дак буря и дождь не дамажат мара под бктт

2024-02-04 05:51 UTC, Ghostkokos approved these changes
В целом хорошо но вопрос по урону по марам остаётся ибо существуют приказы СЛа которые анулируют урон от бури или дождя следовательно может быть такое что погодные условия станут изи возможностью пуша до пещер, но нужно посмотреть

2024-02-08 13:40 UTC, lorianss commented
Hive: Mature Carrier (Den) has died at Northwest Colony Grounds! 
Hive: Young Warrior (Brutus) has died at Northwest Colony Grounds!

OOC: Ge4ok: КОДЕРЫ ПИДАРЫ

2024-02-10 05:49 UTC, fe-ed commented
Таки понял что это много

2024-02-10 06:55 UTC, closed without merging