Второе пришествие быка (bull rework)
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #424
Opened 2024-02-10 14:42 UTC by MeowEmiya

Удалён рывок у быка.

Изменяет механику способностей быка, теперь вместо необходимости разгона, способности применяются по нажатию. При использования способности происходит короткий виндап, после чего бык ускоряется, эффекты от рывков применяются при атаке, после применения способности уходят на КД.

Добавлена новая способность, "acid charge" при применении бык наносит себе небольшой урон, после чего начинает оставлять за собой кислотные лужи.
Добавлена новая примо способность "shattering charge" имеет перезарядку в 8 минут, имеет схожу механнику с остальными рывками, но при атаке ломает предмет, который находится в руках у цели.
Изменён headbutt, теперь вместо долгого стана, цель отбрасывается на 6 тайлов.

Увеличена броня от взрывов до 20.

2024-02-10 15:03 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +	succeed_activate()//
```suggestion
	succeed_activate()
```

2024-02-10 15:04 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +	if(!do_after(X, 10, NONE, X, BUSY_ICON_DANGER))
```suggestion
	if(!do_after(X, 1 SECONDS, NONE, X, BUSY_ICON_DANGER))
```
Так удобнее

2024-02-10 15:13 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +	qdel(broken_item)
```suggestion
	broken_item.deconstruct(FALSE)
```
Ты же не прям таки удаляешь из кода вселенной этот предмет, правда?

2024-02-10 15:21 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +	if(!do_after(X, 10, NONE, X, BUSY_ICON_DANGER))
```suggestion
	if(!do_after(X, 1 SECONDS, NONE, X, BUSY_ICON_DANGER))
```

2024-02-10 15:30 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +	if(!do_after(X, 5, NONE, X, BUSY_ICON_DANGER))
```suggestion
	if(!do_after(X, 0.5 SECONDS, NONE, X, BUSY_ICON_DANGER))
```

2024-02-10 15:30 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +	if(!do_after(X, 10, NONE, X, BUSY_ICON_DANGER))
```suggestion
	if(!do_after(X, 1 SECONDS, NONE, X, BUSY_ICON_DANGER))
```

2024-02-10 19:05 UTC, definitelynotspaghetti commented
Бык быстрый, но от удаления не убежит.

2024-02-11 05:24 UTC, Ghostkokos commented
С примо обилкой нужно что то решать, ибо будет сильно когда тебе в 4 Булла удаляют сг из игры

2024-02-20 09:36 UTC, Helg2 commented
Кислотному рывку было бы логично потреблять меньше плазмы за счёт того что он также использует хп

2024-03-11 15:29 UTC, Dgeen requested changes
Вроде нормально, но в чем смысл прока afterimage_act я не понял

2024-03-11 15:29 UTC, Dgeen commented on code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
> +	var/acid_charge_damage = 30
Ненужный вар, можешь использовать дефайн вместо него

2024-03-11 15:29 UTC, Dgeen commented on code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
> +
Прок, который делает ничего? Зачем ты его добавил?

2024-03-11 15:29 UTC, Dgeen commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +		O.afterimage_act(X)
Единственное место где ты вызываешь прок, который сам добавил и который ничего не делает?

2024-03-11 15:29 UTC, Dgeen commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +		return
Думаю это можно перенести в can_use_ability

2024-03-11 15:29 UTC, Dgeen commented on code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
> +		COMSIG_XENOMORPH_ATTACK_LIVING,
В асид чардж сигнал на атаку не регистрировался

2024-03-11 17:32 UTC, Dgeen approved these changes

2024-03-16 16:31 UTC, definitelynotspaghetti approved these changes

2024-03-16 16:32 UTC, Blundir approved these changes

2024-03-16 16:32 UTC, merged