Synth cant attack
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #464
Opened 2024-02-28 19:45 UTC by lorianss

## About The Pull Request

Your program does not allow you to use this.
Синты больше не могут дратся на уровне кода. Во всех смыслах.

## Why It's Good For The Game

Это позволит убрать правило о боесинтах и закрепит его на уровне кода.
Желание ГА.

## Changelog
Синт больше не может бить ксеносам предметом в руке
Синт больше не может кидать предметы
Синт больше не может стрелять метательными ножами (таков код..)

ПОЖАЛУЙСТА ДРУЗЬЯ, ЕСЛИ ВЫ ВИДИТЕ КАК МОЖНО УЛУЧШИТЬ КОД, ИЛИ Я ЧТО ТО УПУСТИЛ ИЗ БОЕВЫХ ВОЗМОЖНОСТЕЙ СИНТОВ, ИЛИ ЕЩЁ ЧТО ТО, ПИШИТЕ!!!

2024-02-29 03:43 UTC, Ro2tCrab commented
Не скажу что хорошо это.
 По сути, данный ПР карает синтетов за деятельность вне шипа, ибо хочешь или нет, но самозащита это необходимый минимум. У синтета прямо под носом начнут убивать пациента, мешать ему строить или убьют в процессе ремонта себя.
Есть причина по которой саппортам дают хотя бы минимальную боевую мощь.
Он и так слабее среднего морпеха, куда дальше то?

2024-02-29 07:37 UTC, Ghostkokos commented
Чё-то вы пересрали пастами можно же короче написать. Хуйня отменяй

2024-02-29 09:55 UTC, Dgeen requested changes
Добавь 
`CHECK_BITFIELD(flags_item, SYNTH_RESTRICTED) && !CONFIG_GET(flag/allow_synthetic_gun_use)`
во все проверки
Также отдельно проверь работу плазмакаттера и паверфиста, они переопределяют attack

2024-02-29 09:55 UTC, Dgeen commented on code/_onclick/item_attack.dm
> +
Возможно стоит перенести это на уровень `/obj/item/weapon/attack` (в этом случае можно будет ещё убрать проверку на isxeno)
А ещё тут опечатка и следует использовать && вместо &

2024-02-29 09:55 UTC, Dgeen commented on code/modules/mob/living/carbon/carbon.dm
> +
Так же стоит перенести на уровень` /mob/living/carbon/human,` нам не нужна лишняя проверка при броске вещей ксенами

2024-02-29 12:30 UTC, homexp13 commented
> Моего сладенького мейна пытаются занёрфить, поэтому пришло время вмешаться и хотя бы ПОПЫТАТЬСЯ вразумить долбоёбов на проводе.

1) "Синтетики должны держать в приоритете самосохранение. Они не должны подвергать себя опасности, только если нет более приоритетных задач, которые значительно помогут миссии" (великая и могучая вики) - если ты считаешь что самая приоритетная задача для синта это резать стены когда рядом бегают ксеноморфы которые могут за это дать пизды это скилл ишуй. Да и никто собственно не мешает это делать, просто не пизди ксенов резаком, если это действительно так необходимо.
2) "Как умный синт сможет выполнять свою работу, допустим, санитара, если его пациента может долбить в анус любой мимосруня" - ты и не должен отвечать. Синт вступает в бой **только** в случае **само**обороны. Если кого то ебут, даже пациента, ты не должен по своим законом пиздить ксена чтобы его отгнать, если он не пиздит тебя.

И если ты думаешь что я сам не ебашил в застройку с резаком или не защищал критованных маров от ксен, то это не так, но и не стоит воспринимать это как норму. Синт должен вступать бой только чтобы защитить свою жизнь, что без жёстких ограничений невозможно.
Тут опять же либо послаблять рули, чтобы синту позвалялась большая свобода и не было путаници между правилами/педалями/игроками либо обходится такими методами, что является меньшим злом я хз.

2024-03-01 06:15 UTC, CabbageOnTable commented
Чтобы не плакали надо синтам как на кумах дать возможность брать рунек в захват дизармить их в стан и т.п. Но только быстрые легкие касты, то есть воина уже например нельзя.

2024-03-01 12:28 UTC, Ghostkokos commented
С таким синтом не грез и ввести рюкзак с СМ хуле

2024-03-05 10:44 UTC, Helg2 commented on code/modules/mob/living/carbon/carbon.dm
> +
Рантаймит из-за этого также.

2024-09-05 12:02 UTC, closed without merging