Hivemind minimap and silo like warning[definitely not modular]
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #490
Opened 2024-03-09 12:11 UTC by Lentye

Adds hivemind minimap icon and signal alike silo

## About The Pull Request

Создает иконки ядру ХМа, а так же оповещение хайву подобну силу(поидеи, не смог в одиночку это проверить, обычное оповещение со звуком самому ХМу работает исправно)
Был вынужден закоментить исходный код ибо при попытке оверрайднуть в модуляр код исполнялся дважды вызывая рантаймы

## Why It's Good For The Game

Не нужно больше вручную искать где у ебаного ХМа ядро и спрашивать об этом
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/117032431/6a82f360-b840-4443-a930-487c5a35e545)
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/117032431/cfda3b83-b6c1-4cbf-be17-fb61ecefc045)
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/117032431/5ce73296-675a-44fc-a84f-20f3abb0cf21)

## Changelog

:cl:
imageadd: hivemind minimap icon+silo alike warn
/:cl:

2024-03-09 12:21 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +/*obj/structure/xeno/hivemindcore/Initialize(mapload)
```suggestion
/* overriden by RU tgmc needs, modular_RUTGMC/mob/xeno/castes/hivemind
obj/structure/xeno/hivemindcore/Initialize(mapload)
```

2024-03-09 12:21 UTC, Helg2 commented on code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +/*obj/structure/xeno/hivemindcore/proc/hivemind_proxy_alert(datum/source, atom/movable/hostile)
```suggestion
/* overriden by RU tgmc needs, modular_RUTGMC/mob/xeno/castes/hivemind
obj/structure/xeno/hivemindcore/proc/hivemind_proxy_alert(datum/source, atom/movable/hostile)
```

2024-03-09 12:21 UTC, Helg2 commented on modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	SSminimaps.add_marker(src, MINIMAP_FLAG_XENO, image('modular_RUtgmc/icons/UI_icons/map_blips.dmi', null, "hivemindcore[warning ? "_warn" : "_passive"]")) // RU TGMC edit - map blips
```suggestion
	SSminimaps.add_marker(src, MINIMAP_FLAG_XENO, image('modular_RUtgmc/icons/UI_icons/map_blips.dmi', null, "hivemindcore[warning ? "_warn" : "_passive"]"))
```

2024-03-11 15:52 UTC, Dgeen requested changes

2024-03-11 15:52 UTC, Dgeen commented on modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +	addtimer(CALLBACK(src, PROC_REF(clear_warning)), XENO_SILO_DETECTION_COOLDOWN) //clear warning
```suggestion
	addtimer(CALLBACK(src, PROC_REF(clear_warning)), XENO_HIVEMIND_DETECTION_COOLDOWN) //clear warning
```

2024-03-11 15:52 UTC, Dgeen commented on modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +
INITIALIZE_HINT_LATELOAD используется если мы хотим вызвать прок LateInitialize, которого у ядра нет. Эта строчка здесь не нужна

2024-03-12 14:35 UTC, Lentye commented on modular_RUtgmc/code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
> +
справедливо

2024-03-14 18:33 UTC, Dgeen approved these changes

2024-04-03 17:06 UTC, Lentye commented
@Blundir  Тест-мерджнем все-таки или что-то еще надо сделать?

2024-04-05 19:06 UTC, Lentye commented
и снова седая ночь и только ей доверяю я...Нахуя-то я ПОСЛЕ ручного твоего запуска теста по совету хеглега дал мизерное изменение-поставил пробел xd
![image](https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/assets/117032431/c309db5e-8ec6-43ea-ae98-9124527181a8)

2024-06-19 12:47 UTC, Lentye commented
а как догадаться что не так? xd

2024-06-19 13:06 UTC, closed without merging