Defiler changes
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #495
Opened 2024-03-11 10:48 UTC by MeowEmiya

Основано на https://github.com/Cosmic-Overlord/RU-TerraGov-Marine-Corps/pull/123

Теперь если в маре больше одного вида ксенотоксинов, включая гемодил, то ему накладывается стан на три секунды.
Само замедление от реагентов у гемодила работает как раньше, стан лишь дополнительный эффект.
Комбо тратит больше половины запаса плазмы. Гемодил после стана полностью пуржится.

Дефайл в одну кнопку не фанни.

Текущее однокнопочное примо было заменено на откладывание газовых яиц, газ в которых зависит от выбранного токсина. В отличии от обычных яиц, вырастают мгновенно, имеют сильно сниженный виндап на посадку, порезанные КД и плазмакост. 

В текущем состоянии, яйца слишком неудобны для использования после открытия створок, изменение наверняка это исправит.

2024-03-11 14:37 UTC, homexp13 commented on modular_RUtgmc/code/modules/reagents/reagents/toxin.dm
> +	return ..()
а он заново не будет тот же код вызывать? Надо наверно в корне задокументировать метод

2024-03-11 14:42 UTC, homexp13 commented on modular_RUtgmc/code/modules/reagents/reagents/toxin.dm
> +			reagent_amount += L.reagents.get_reagent_amount(/datum/reagent/toxin/xeno_hemodile)
Это наверно надо из цикла вынести иначе reagent_amount будет больше чем хемодила в крови, на удаление реагента далее это не влияет напрямую но всё равно странно

2024-03-14 09:06 UTC, lorianss commented
Почему гемодилу делают комбинацию со станом, полностью его выводящем когда у него есть своя роль в виде замедла мара? Почему интеракцию со станом, нельзя было дать другому реагенту, трасвитоксу или как он там, который никем не используется, потому что просто переводит урон в токсины, без доп урона.
Новое примо абсолютно уебанское, не хочу оскорблять никого поэтому просто сделают вид что этого нет. Просто надеюсь все понимают что нужно будет делать другое, нахуя срать эту заглушку я не знаю.
Так же я не заметил фикса бага, из за которого дефайлер бьёт две атаки, хотя по коду он всегда бил три, верю в то что его уже пофиксили а я это пропустил.
Понижение урона я вообще не понял смысла, какая имено у дефайлера роль, раз он не достоин своих 26 мили урона в тычку? Я всегда думал что он мили боец ближнего боя который сокращает дистанцию, который к тому же подвержен стагеру.

не хочу пасту долгую писать, так что закончу тут

2024-03-14 18:00 UTC, definitelynotspaghetti requested changes
Примо поменять надо. Сделай так, что он мгновенно спавнит облако дыма, радиусом в 2(или 3). А газовое яйцо можешь обычной абилкой сделать.

2024-04-04 13:50 UTC, Blundir approved these changes

2024-04-11 17:21 UTC, closed without merging