Big defiler and his little friend sentinel
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #643
Opened 2024-06-12 11:47 UTC by homexp13

## About The Pull Request

### дефайлер
слеш кислотой накладывает стаки токсинов
### сент
трасвитоксовый плевок

## Why It's Good For The Game

ПР напрален на взаимодействие каст между собой, т.к нейро вырезали, то стало сложнее комбить за счёт реагентов. Думаю такое взаимодействие пойдёт в плюс

2024-06-12 13:25 UTC, Ro2tCrab commented
closes 641

2024-06-12 19:15 UTC, definitelynotspaghetti requested changes
Химические плевки не одобряем.

2024-06-12 20:05 UTC, definitelynotspaghetti approved these changes

2024-06-18 07:25 UTC, Blundir approved these changes

2024-06-18 07:25 UTC, merged