[MODULAR]SG-62 changes
Cosmic-Overlord/RU-TerraGov-Marine-Corps pull request #74
Opened 2023-10-30 23:07 UTC by definitelynotspaghetti

## About The Pull Request
Уменьшен дилей между выстрелами.
Подствол стреляет точнее.
Дальность стрельбы подствола уменьшена до 6 тайлов, но взамен некоторые боеприпасы стали чуть сильнее
highimpact - секунда стаггера и секунда замедления
heavyrubber - две секунды замедления
plasmaloss - помимо изначального эффекта, теперь спавнит облако тангфута при попадании.
tungsten - микростан и отбрасывание.
Добавил коробку на 200 патронов в карго.
https://discord.com/channels/1042907674754437140/1059662710217908245/1168662537978515566

## Why It's Good For The Game
Интересная пушка, но, как оказалось, довольно слаба. Надо баффнуть немного, может станет лучше.

2023-10-30 23:38 UTC, homexp13 commented
Зачем всё вырезать и копировать? Переопредели нужные тебе характеристики в модульной папке

2023-10-31 08:33 UTC, definitelynotspaghetti commented
Все норм.

2023-10-31 08:38 UTC, homexp13 commented
Ну да вместо того чтобы изменить несколько значений просто всё контрл в конртл ц, что под руку попалось,, всё норм

2023-11-01 13:13 UTC, homexp13 commented on modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
> +	staggerstun(M, P, stagger = 3, slowdown = 1, max_range = 6)
Почему стагер не в секундах?

2023-11-01 13:18 UTC, homexp13 commented on modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
> +	max_range = 6
Ты точно уверен что это нужно? Он же позиционирует себя по типу дмр, зачем ограничивать дальность?

2023-11-02 23:46 UTC, Blundir approved these changes

2023-11-02 23:47 UTC, Blundir requested changes
Хотя комменты валидны

2023-11-03 17:42 UTC, homexp13 commented on modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
> +	staggerstun(M, P, weaken = 2 SECONDS, stagger = 2 SECONDS, knockback = 1, max_range = 12)
Отбрасывание с 12 тайлов?

2023-11-05 19:45 UTC, definitelynotspaghetti commented on modular_RUtgmc/code/modules/projectiles/guns/rifles.dm
> +	staggerstun(M, P, weaken = 2 SECONDS, stagger = 2 SECONDS, knockback = 1, max_range = 12)
Это с оффов. Раз у них прописано 12 ренжа, пусть и у нас будет 12

2023-11-05 19:50 UTC, Blundir approved these changes

2023-11-05 20:12 UTC, merged